monitor_ip: "{{ hostvars['monitor_node']['ansible_host'] }}"
worker_ips: "{{ groups['workers'] | map('extract', hostvars, ['ansible_host']) | list }}"
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/sree.pem