- name: Setup Node Exporter and Promtail on worker nodes
  hosts: workers
  become: yes
  vars:
    monitor_node_ip: "13.201.98.75"  # internal IP of monitor node
    ssh_key_path: "~/sree.pem"  # absolute path to your private key

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
          - python3-docker
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure user can run Docker without sudo (optional)
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Run Node Exporter container
      docker_container:
        name: node_exporter
        image: quay.io/prometheus/node-exporter
        ports:
          - "9100:9100"
        restart_policy: always
        volumes:
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /:/rootfs:ro
        command:
          - "--path.procfs=/host/proc"
          - "--path.sysfs=/host/sys"
          - "--path.rootfs=/rootfs"

    - name: Copy Promtail config to host
      template:
        src: ~/portable_monitoring_agent/monitoring-deploy/files/promtail-config.yaml
        dest: /opt/promtail-config.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Run Promtail container
      docker_container:
        name: promtail
        image: grafana/promtail:2.9.4
        volumes:
          - /var/log:/var/log
          - /opt/promtail-config.yaml:/etc/promtail/promtail.yaml
        env:
          MONITOR_IP: "{{ monitor_ip }}"
        command: -config.file=/etc/promtail/promtail.yaml
        restart_policy: always
