#!/usr/bin/env bash
# =============================================================================
# generate-inventory.sh
#
# Reads Terraform outputs and writes monitoring-deploy/inventory.ini
# ready for Ansible to use — no manual copy-paste of IP addresses.
#
# Run this from the terraform/aws/ directory AFTER terraform apply:
#   cd terraform/aws
#   ./generate-inventory.sh
#
# Options:
#   --key-file  PATH   Path to your .pem file  (default: ~/sree.pem)
#   --win-pass  PASS   Windows Administrator password
#   --dry-run          Print the inventory without writing it
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
INVENTORY_FILE="${REPO_ROOT}/monitoring-deploy/inventory.ini"

# ─── Defaults ─────────────────────────────────────────────────────────────────
KEY_FILE="~/sree.pem"
WIN_PASS=""
DRY_RUN=false

# ─── Argument parsing ─────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --key-file) KEY_FILE="$2"; shift 2 ;;
    --win-pass) WIN_PASS="$2"; shift 2 ;;
    --dry-run)  DRY_RUN=true; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ─── Checks ───────────────────────────────────────────────────────────────────
command -v terraform &>/dev/null || { echo "ERROR: terraform not found."; exit 1; }
command -v jq        &>/dev/null || { echo "ERROR: jq not found. Install with: sudo apt install jq"; exit 1; }

if ! terraform output monitor_public_ip &>/dev/null 2>&1; then
  echo "ERROR: No Terraform outputs found. Run 'terraform apply' first."
  exit 1
fi

# ─── Read Terraform outputs ───────────────────────────────────────────────────
echo "Reading Terraform outputs..."

MONITOR_IP=$(terraform output -raw monitor_public_ip)
MONITOR_PRIVATE_IP=$(terraform output -raw monitor_private_ip)

# Linux workers — JSON array → newline-separated list
LINUX_PUBLIC_IPS=$(terraform output -json linux_worker_public_ips | jq -r '.[]')

# Windows workers — JSON array → newline-separated list
WIN_PUBLIC_IPS=$(terraform output -json windows_worker_public_ips 2>/dev/null | jq -r '.[]' 2>/dev/null || echo "")

EKS_CLUSTER=$(terraform output -raw eks_cluster_name 2>/dev/null || echo "")
AWS_REGION=$(terraform output -raw eks_cluster_name 2>/dev/null \
  && terraform -chdir="${SCRIPT_DIR}" output -json 2>/dev/null \
  | jq -r '.aws_region.value // "us-east-1"' 2>/dev/null || echo "us-east-1")

# ─── Build Linux workers section ──────────────────────────────────────────────
LINUX_WORKERS_BLOCK=""
i=1
while IFS= read -r ip; do
  [[ -z "$ip" ]] && continue
  LINUX_WORKERS_BLOCK+="linux_worker${i} ansible_host=${ip} ansible_user=ubuntu"$'\n'
  ((i++))
done <<< "$LINUX_PUBLIC_IPS"

# ─── Build Windows workers section ────────────────────────────────────────────
WINDOWS_WORKERS_BLOCK=""
i=1
while IFS= read -r ip; do
  [[ -z "$ip" ]] && continue
  WINDOWS_WORKERS_BLOCK+="windows_worker${i} ansible_host=${ip}"$'\n'
  ((i++))
done <<< "$WIN_PUBLIC_IPS"

# ─── Compose inventory ────────────────────────────────────────────────────────
INVENTORY=$(cat <<EOF
# =============================================================================
# Ansible Inventory — AUTO-GENERATED by terraform/aws/generate-inventory.sh
# Do not edit manually. Re-run the script after any terraform apply.
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

[monitor]
monitor_node ansible_host=${MONITOR_IP} ansible_user=ubuntu

[workers]
${LINUX_WORKERS_BLOCK}
[windows_workers]
${WINDOWS_WORKERS_BLOCK}
[windows_workers:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_user=Administrator
${WIN_PASS:+ansible_password=${WIN_PASS}}
ansible_port=5985

[all:vars]
ansible_ssh_private_key_file=${KEY_FILE}
monitor_node_ip=${MONITOR_IP}
monitor_private_ip=${MONITOR_PRIVATE_IP}
EOF
)

# ─── Output ───────────────────────────────────────────────────────────────────
if $DRY_RUN; then
  echo ""
  echo "=== DRY RUN — inventory that would be written to ${INVENTORY_FILE} ==="
  echo ""
  echo "$INVENTORY"
  echo ""
  echo "=== (not written) ==="
else
  echo "$INVENTORY" > "${INVENTORY_FILE}"
  echo ""
  echo "Written to: ${INVENTORY_FILE}"
fi

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  Infrastructure Summary"
echo "============================================================"
echo "  Monitor server:   ${MONITOR_IP}"
echo "  Linux workers:    $(echo "$LINUX_PUBLIC_IPS" | grep -c . || echo 0) node(s)"
[[ -n "$WIN_PUBLIC_IPS" ]] && \
echo "  Windows workers:  $(echo "$WIN_PUBLIC_IPS" | grep -c . || echo 0) node(s)"
[[ -n "$EKS_CLUSTER" ]] && \
echo "  EKS cluster:      ${EKS_CLUSTER}"
echo "------------------------------------------------------------"
echo ""
echo "  Grafana:      http://${MONITOR_IP}:3000  (admin / admin)"
echo "  Prometheus:   http://${MONITOR_IP}:9090"
echo "  Loki:         http://${MONITOR_IP}:3100"
echo "  Alertmanager: http://${MONITOR_IP}:9093"
echo ""
[[ -n "$EKS_CLUSTER" ]] && cat <<EKS
  Configure kubectl:
    aws eks update-kubeconfig --region ${AWS_REGION} --name ${EKS_CLUSTER}

EKS
echo "============================================================"
echo ""
echo "Next steps:"
echo "  1. Test Ansible connectivity:  cd ../../ && ansible all -i monitoring-deploy/inventory.ini -m ping"
echo "  2. Deploy monitoring stack:    ./install.sh --all"
echo ""
