[monitor]
localhost ansible_user="{{ ansible_user }}"

[workers]
"{{ worker_ip }}" ansible_user="{{ ansible_user }}"

[all:vars]
ansible_ssh_private_key_file="{{ ansible_ssh_private_key_file }}"
monitor_node_ip="{{ monitor_ip }}"